//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeatVibezPOS.NeatVibez_Server {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NeatVibez_Server.INeatVibez_Server")]
    public interface INeatVibez_Server {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/CheckConnection", ReplyAction="http://tempuri.org/INeatVibez_Server/CheckConnectionResponse")]
        bool CheckConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveSystemSettings", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveSystemSettingsResponse")]
        System.Data.DataTable RetrieveSystemSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/UpdateSystemSettings", ReplyAction="http://tempuri.org/INeatVibez_Server/UpdateSystemSettingsResponse")]
        bool UpdateSystemSettings(string SystemName, byte[] SystemLogo, string SystemPhone, int SystemReceiptBlankSpaces, string SystemPrinterName, int SystemIncludeLogoInReceipt, decimal SystemTax);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveItemTypeName", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveItemTypeNameResponse")]
        string RetrieveItemTypeName(int ItemTypeIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveWarehouseName", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveWarehouseNameResponse")]
        string RetrieveWarehouseName(int WarehouseIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveFavoriteCategoryName", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveFavoriteCategoryNameResponse")]
        string RetrieveFavoriteCategoryName(int CategoryIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveCashierNames", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveCashierNamesResponse")]
        System.Collections.Generic.List<string> RetrieveCashierNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveItemTypeID", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveItemTypeIDResponse")]
        int RetrieveItemTypeID(string ItemTypeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveWarehouseID", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveWarehouseIDResponse")]
        int RetrieveWarehouseID(string WarehouseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveFavoriteCategoryID", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveFavoriteCategoryIDResponse")]
        int RetrieveFavoriteCategoryID(string CategoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveItemTypes", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveItemTypesResponse")]
        System.Collections.Generic.List<Dependencies.ItemType> RetrieveItemTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveWarehouses", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveWarehousesResponse")]
        System.Collections.Generic.List<Dependencies.Warehouse> RetrieveWarehouses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveFavoriteCategories", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveFavoriteCategoriesResponse")]
        System.Collections.Generic.List<Dependencies.Category> RetrieveFavoriteCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveLoginLogoutInfo", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveLoginLogoutInfoResponse")]
        System.Data.DataTable RetrieveLoginLogoutInfo(System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveUsersList", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveUsersListResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Account>, System.Data.DataTable> RetrieveUsersList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/GetRetrieveCustomers", ReplyAction="http://tempuri.org/INeatVibez_Server/GetRetrieveCustomersResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Customer>, System.Data.DataTable> GetRetrieveCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/GetRetrieveVendors", ReplyAction="http://tempuri.org/INeatVibez_Server/GetRetrieveVendorsResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Customer>, System.Data.DataTable> GetRetrieveVendors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/CheckAdmin", ReplyAction="http://tempuri.org/INeatVibez_Server/CheckAdminResponse")]
        bool CheckAdmin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RegisterAdmin", ReplyAction="http://tempuri.org/INeatVibez_Server/RegisterAdminResponse")]
        bool RegisterAdmin(Dependencies.Account AccountToRegister);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/LogLogout", ReplyAction="http://tempuri.org/INeatVibez_Server/LogLogoutResponse")]
        void LogLogout(string cashierName, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/LogLogin", ReplyAction="http://tempuri.org/INeatVibez_Server/LogLoginResponse")]
        void LogLogin(string cashierName, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/Login", ReplyAction="http://tempuri.org/INeatVibez_Server/LoginResponse")]
        System.Tuple<bool, string, bool> Login(Dependencies.Account AccountToLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/Register", ReplyAction="http://tempuri.org/INeatVibez_Server/RegisterResponse")]
        bool Register(Dependencies.Account AccountToRegister, string UID, int AdminOrNot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/DeleteFavoriteItem", ReplyAction="http://tempuri.org/INeatVibez_Server/DeleteFavoriteItemResponse")]
        bool DeleteFavoriteItem(string ItemBarCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/AddFavoriteItem", ReplyAction="http://tempuri.org/INeatVibez_Server/AddFavoriteItemResponse")]
        bool AddFavoriteItem(string ItemName, string ItemBarCode, int ItemQuantity, decimal ItemPrice, decimal ItemPriceTax, decimal Category, System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/SaveRegisterClose", ReplyAction="http://tempuri.org/INeatVibez_Server/SaveRegisterCloseResponse")]
        bool SaveRegisterClose(string cashierName, decimal moneyInRegister);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/SaveRegisterOpen", ReplyAction="http://tempuri.org/INeatVibez_Server/SaveRegisterOpenResponse")]
        bool SaveRegisterOpen(string cashierName, decimal moneyInRegister);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/SearchWarehouseInventoryItems", ReplyAction="http://tempuri.org/INeatVibez_Server/SearchWarehouseInventoryItemsResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> SearchWarehouseInventoryItems(int WarehouseID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/SearchInventoryItems", ReplyAction="http://tempuri.org/INeatVibez_Server/SearchInventoryItemsResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> SearchInventoryItems(string ItemName, string ItemBarCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/SearchInventoryItemsWithBarCode", ReplyAction="http://tempuri.org/INeatVibez_Server/SearchInventoryItemsWithBarCodeResponse")]
        Dependencies.Item SearchInventoryItemsWithBarCode(string ItemBarCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveUnPortedBills", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveUnPortedBillsResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Bill>, System.Data.DataTable> RetrieveUnPortedBills();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrievePortedBills", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrievePortedBillsResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Bill>, System.Data.DataTable> RetrievePortedBills();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveVendorBills", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveVendorBillsResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Bill>, System.Data.DataTable> RetrieveVendorBills();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveTaxZReport", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveTaxZReportResponse")]
        System.Data.DataTable RetrieveTaxZReport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveBills", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveBillsResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Bill>, System.Data.DataTable> RetrieveBills();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveCapitalRevenue", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveCapitalRevenueResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> RetrieveCapitalRevenue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveExports", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveExportsResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> RetrieveExports();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveImports", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveImportsResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> RetrieveImports();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveLeastBoughtItems", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveLeastBoughtItemsResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> RetrieveLeastBoughtItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveMostBoughtItems", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveMostBoughtItemsResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> RetrieveMostBoughtItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveAccountAuthority", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveAccountAuthorityResponse")]
        int RetrieveAccountAuthority(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveUserPermissions", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveUserPermissionsResponse")]
        Dependencies.Account RetrieveUserPermissions(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveItemPictureFromBarCode", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveItemPictureFromBarCodeResponse")]
        Dependencies.Item RetrieveItemPictureFromBarCode(string ItemBarCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveItemsQuantityDates", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveItemsQuantityDatesResponse")]
        Dependencies.Item RetrieveItemsQuantityDates(string ItemBarCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveItems", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveItemsResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> RetrieveItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveEmployees", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveEmployeesResponse")]
        System.Data.DataTable RetrieveEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveUsers", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveUsersResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Account>, System.Data.DataTable> RetrieveUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveVendorBillItems", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveVendorBillItemsResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> RetrieveVendorBillItems(int BillNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveBillItems", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveBillItemsResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> RetrieveBillItems(int BillNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveBillItemsProfit", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveBillItemsProfitResponse")]
        System.Data.DataTable RetrieveBillItemsProfit(System.DateTime Date1, System.DateTime Date2, int ItemTypeID, string CashierName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveReturnedItems", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveReturnedItemsResponse")]
        System.Data.DataTable RetrieveReturnedItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveFavoriteItems", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveFavoriteItemsResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> RetrieveFavoriteItems(int Category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/GetCapitalAmount", ReplyAction="http://tempuri.org/INeatVibez_Server/GetCapitalAmountResponse")]
        decimal GetCapitalAmount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/GetOpenRegisterAmount", ReplyAction="http://tempuri.org/INeatVibez_Server/GetOpenRegisterAmountResponse")]
        decimal GetOpenRegisterAmount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/GetTotalSalesAmountCloseCash", ReplyAction="http://tempuri.org/INeatVibez_Server/GetTotalSalesAmountCloseCashResponse")]
        decimal GetTotalSalesAmountCloseCash();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/GetTotalSalesAmount", ReplyAction="http://tempuri.org/INeatVibez_Server/GetTotalSalesAmountResponse")]
        decimal GetTotalSalesAmount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/GetLastOpenRegisterDate", ReplyAction="http://tempuri.org/INeatVibez_Server/GetLastOpenRegisterDateResponse")]
        string GetLastOpenRegisterDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/InsertExpense", ReplyAction="http://tempuri.org/INeatVibez_Server/InsertExpenseResponse")]
        bool InsertExpense(string ExpenseName, decimal ExpenseCost, string EmployeeName, System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/InsertDeduction", ReplyAction="http://tempuri.org/INeatVibez_Server/InsertDeductionResponse")]
        bool InsertDeduction(int EmployeeID, System.DateTime Date, decimal Deduction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/InsertDayOff", ReplyAction="http://tempuri.org/INeatVibez_Server/InsertDayOffResponse")]
        bool InsertDayOff(int EmployeeID, System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/InsertAbsence", ReplyAction="http://tempuri.org/INeatVibez_Server/InsertAbsenceResponse")]
        bool InsertAbsence(int EmployeeID, System.DateTime Date, int Hours);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/InsertEmployee", ReplyAction="http://tempuri.org/INeatVibez_Server/InsertEmployeeResponse")]
        bool InsertEmployee(string EmployeeName, decimal Salary, string Phone, string Address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/InsertItem", ReplyAction="http://tempuri.org/INeatVibez_Server/InsertItemResponse")]
        bool InsertItem(Dependencies.Item ItemToInsert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/DeleteItemType", ReplyAction="http://tempuri.org/INeatVibez_Server/DeleteItemTypeResponse")]
        bool DeleteItemType(int ItemTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/DeleteWarehouse", ReplyAction="http://tempuri.org/INeatVibez_Server/DeleteWarehouseResponse")]
        bool DeleteWarehouse(int WarehouseID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/DeleteFavoriteCategory", ReplyAction="http://tempuri.org/INeatVibez_Server/DeleteFavoriteCategoryResponse")]
        bool DeleteFavoriteCategory(int FavoriteCategoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/UpdateItemTypes", ReplyAction="http://tempuri.org/INeatVibez_Server/UpdateItemTypesResponse")]
        bool UpdateItemTypes(int ItemTypeID, string ItemTypeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/UpdateWarehouses", ReplyAction="http://tempuri.org/INeatVibez_Server/UpdateWarehousesResponse")]
        bool UpdateWarehouses(int WarehouseID, string WarehouseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/UpdateFavoriteCategories", ReplyAction="http://tempuri.org/INeatVibez_Server/UpdateFavoriteCategoriesResponse")]
        bool UpdateFavoriteCategories(int FavoriteCategoryID, string FavoriteCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/InsertItemType", ReplyAction="http://tempuri.org/INeatVibez_Server/InsertItemTypeResponse")]
        bool InsertItemType(string ItemTypeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/InsertWarehouse", ReplyAction="http://tempuri.org/INeatVibez_Server/InsertWarehouseResponse")]
        bool InsertWarehouse(string WarehouseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/InsertFavoriteCategory", ReplyAction="http://tempuri.org/INeatVibez_Server/InsertFavoriteCategoryResponse")]
        bool InsertFavoriteCategory(string FavoriteCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/DeletesCustomer", ReplyAction="http://tempuri.org/INeatVibez_Server/DeletesCustomerResponse")]
        bool DeletesCustomer(string CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RegisterCustomer", ReplyAction="http://tempuri.org/INeatVibez_Server/RegisterCustomerResponse")]
        bool RegisterCustomer(Dependencies.Customer CustomerToInsert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RegisterVendor", ReplyAction="http://tempuri.org/INeatVibez_Server/RegisterVendorResponse")]
        bool RegisterVendor(Dependencies.Customer CustomerToInsert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/DeleteAbsence", ReplyAction="http://tempuri.org/INeatVibez_Server/DeleteAbsenceResponse")]
        bool DeleteAbsence(int AbsenceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/DeleteEmployee", ReplyAction="http://tempuri.org/INeatVibez_Server/DeleteEmployeeResponse")]
        bool DeleteEmployee(int EmployeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/DeleteUser", ReplyAction="http://tempuri.org/INeatVibez_Server/DeleteUserResponse")]
        bool DeleteUser(Dependencies.Account UserToUpdate, string cashierName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/AddSaleOnItems", ReplyAction="http://tempuri.org/INeatVibez_Server/AddSaleOnItemsResponse")]
        bool AddSaleOnItems(System.Collections.Generic.List<Dependencies.Item> saleItems);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/AddItemToCustomer", ReplyAction="http://tempuri.org/INeatVibez_Server/AddItemToCustomerResponse")]
        bool AddItemToCustomer(string ItemBarCode, int CustomerID, decimal CustomerPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/AddVendorBill", ReplyAction="http://tempuri.org/INeatVibez_Server/AddVendorBillResponse")]
        bool AddVendorBill(Dependencies.Bill billToAdd, string cashierName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/PayBill", ReplyAction="http://tempuri.org/INeatVibez_Server/PayBillResponse")]
        bool PayBill(Dependencies.Bill billToAdd, string cashierName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/UpdateEmployee", ReplyAction="http://tempuri.org/INeatVibez_Server/UpdateEmployeeResponse")]
        bool UpdateEmployee(int EmployeeID, string EmployeeName, decimal Salary, string Phone, string Address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/UpdateUser", ReplyAction="http://tempuri.org/INeatVibez_Server/UpdateUserResponse")]
        bool UpdateUser(Dependencies.Account UserToUpdate, string cashierName, int AdminOrNot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/UpdateBill", ReplyAction="http://tempuri.org/INeatVibez_Server/UpdateBillResponse")]
        bool UpdateBill(int BillNumber, string CashierName, decimal TotalAmount, decimal PaidAmount, decimal RemainderAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/ReturnItem", ReplyAction="http://tempuri.org/INeatVibez_Server/ReturnItemResponse")]
        bool ReturnItem(string ItemName, string ItemBarCode, int ItemQuantity, string cashierName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/UpdateItemWarehouse", ReplyAction="http://tempuri.org/INeatVibez_Server/UpdateItemWarehouseResponse")]
        bool UpdateItemWarehouse(System.Collections.Generic.List<Dependencies.Item> ItemsToUpdate, string EmployeeName, int EntryExitType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/UpdateItem", ReplyAction="http://tempuri.org/INeatVibez_Server/UpdateItemResponse")]
        bool UpdateItem(Dependencies.Item ItemToUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/UpdateItemQuantity", ReplyAction="http://tempuri.org/INeatVibez_Server/UpdateItemQuantityResponse")]
        bool UpdateItemQuantity(Dependencies.Item ItemToUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/DeleteItem", ReplyAction="http://tempuri.org/INeatVibez_Server/DeleteItemResponse")]
        bool DeleteItem(string ItemBarCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveLastVendorBillNumberToday", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveLastVendorBillNumberTodayResponse")]
        Dependencies.Bill RetrieveLastVendorBillNumberToday(System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveLastBillNumberToday", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveLastBillNumberTodayResponse")]
        Dependencies.Bill RetrieveLastBillNumberToday();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveItemsQuantity", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveItemsQuantityResponse")]
        System.Collections.Generic.List<Dependencies.Item> RetrieveItemsQuantity(string ItemBarCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveSaleItemsQuantity", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveSaleItemsQuantityResponse")]
        System.Collections.Generic.List<Dependencies.Item> RetrieveSaleItemsQuantity();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveExpireStockToday", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveExpireStockTodayResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> RetrieveExpireStockToday(System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveSaleToday", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveSaleTodayResponse")]
        System.Collections.Generic.List<Dependencies.Item> RetrieveSaleToday(System.DateTime Date, int QuantityEnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/SearchTodayBills", ReplyAction="http://tempuri.org/INeatVibez_Server/SearchTodayBillsResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Bill>, System.Data.DataTable> SearchTodayBills(System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/SearchBills", ReplyAction="http://tempuri.org/INeatVibez_Server/SearchBillsResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Bill>, System.Data.DataTable> SearchBills(int BillNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/GetItemQuantity", ReplyAction="http://tempuri.org/INeatVibez_Server/GetItemQuantityResponse")]
        int GetItemQuantity(string ItemBarCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/RetrieveAbsence", ReplyAction="http://tempuri.org/INeatVibez_Server/RetrieveAbsenceResponse")]
        System.Data.DataTable RetrieveAbsence(System.DateTime Date1, System.DateTime Date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/SearchExpenses", ReplyAction="http://tempuri.org/INeatVibez_Server/SearchExpensesResponse")]
        System.Data.DataTable SearchExpenses(System.DateTime Date1, System.DateTime Date2, string ExpenseName, string EmployeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/SearchItems", ReplyAction="http://tempuri.org/INeatVibez_Server/SearchItemsResponse")]
        System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> SearchItems(string ItemName, string ItemBarCode, int ItemType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/SearchCustomers", ReplyAction="http://tempuri.org/INeatVibez_Server/SearchCustomersResponse")]
        System.Data.DataTable SearchCustomers(string customerName, string customerID, string itemName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INeatVibez_Server/SearchCustomersInfo", ReplyAction="http://tempuri.org/INeatVibez_Server/SearchCustomersInfoResponse")]
        System.Tuple<Dependencies.Customer, System.Data.DataTable> SearchCustomersInfo(string customerName, string customerID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INeatVibez_ServerChannel : NeatVibezPOS.NeatVibez_Server.INeatVibez_Server, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NeatVibez_ServerClient : System.ServiceModel.ClientBase<NeatVibezPOS.NeatVibez_Server.INeatVibez_Server>, NeatVibezPOS.NeatVibez_Server.INeatVibez_Server {
        
        public NeatVibez_ServerClient() {
        }
        
        public NeatVibez_ServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NeatVibez_ServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NeatVibez_ServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NeatVibez_ServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckConnection() {
            return base.Channel.CheckConnection();
        }
        
        public System.Data.DataTable RetrieveSystemSettings() {
            return base.Channel.RetrieveSystemSettings();
        }
        
        public bool UpdateSystemSettings(string SystemName, byte[] SystemLogo, string SystemPhone, int SystemReceiptBlankSpaces, string SystemPrinterName, int SystemIncludeLogoInReceipt, decimal SystemTax) {
            return base.Channel.UpdateSystemSettings(SystemName, SystemLogo, SystemPhone, SystemReceiptBlankSpaces, SystemPrinterName, SystemIncludeLogoInReceipt, SystemTax);
        }
        
        public string RetrieveItemTypeName(int ItemTypeIndex) {
            return base.Channel.RetrieveItemTypeName(ItemTypeIndex);
        }
        
        public string RetrieveWarehouseName(int WarehouseIndex) {
            return base.Channel.RetrieveWarehouseName(WarehouseIndex);
        }
        
        public string RetrieveFavoriteCategoryName(int CategoryIndex) {
            return base.Channel.RetrieveFavoriteCategoryName(CategoryIndex);
        }
        
        public System.Collections.Generic.List<string> RetrieveCashierNames() {
            return base.Channel.RetrieveCashierNames();
        }
        
        public int RetrieveItemTypeID(string ItemTypeName) {
            return base.Channel.RetrieveItemTypeID(ItemTypeName);
        }
        
        public int RetrieveWarehouseID(string WarehouseName) {
            return base.Channel.RetrieveWarehouseID(WarehouseName);
        }
        
        public int RetrieveFavoriteCategoryID(string CategoryName) {
            return base.Channel.RetrieveFavoriteCategoryID(CategoryName);
        }
        
        public System.Collections.Generic.List<Dependencies.ItemType> RetrieveItemTypes() {
            return base.Channel.RetrieveItemTypes();
        }
        
        public System.Collections.Generic.List<Dependencies.Warehouse> RetrieveWarehouses() {
            return base.Channel.RetrieveWarehouses();
        }
        
        public System.Collections.Generic.List<Dependencies.Category> RetrieveFavoriteCategories() {
            return base.Channel.RetrieveFavoriteCategories();
        }
        
        public System.Data.DataTable RetrieveLoginLogoutInfo(System.DateTime Date) {
            return base.Channel.RetrieveLoginLogoutInfo(Date);
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Account>, System.Data.DataTable> RetrieveUsersList() {
            return base.Channel.RetrieveUsersList();
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Customer>, System.Data.DataTable> GetRetrieveCustomers() {
            return base.Channel.GetRetrieveCustomers();
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Customer>, System.Data.DataTable> GetRetrieveVendors() {
            return base.Channel.GetRetrieveVendors();
        }
        
        public bool CheckAdmin() {
            return base.Channel.CheckAdmin();
        }
        
        public bool RegisterAdmin(Dependencies.Account AccountToRegister) {
            return base.Channel.RegisterAdmin(AccountToRegister);
        }
        
        public void LogLogout(string cashierName, System.DateTime date) {
            base.Channel.LogLogout(cashierName, date);
        }
        
        public void LogLogin(string cashierName, System.DateTime date) {
            base.Channel.LogLogin(cashierName, date);
        }
        
        public System.Tuple<bool, string, bool> Login(Dependencies.Account AccountToLogin) {
            return base.Channel.Login(AccountToLogin);
        }
        
        public bool Register(Dependencies.Account AccountToRegister, string UID, int AdminOrNot) {
            return base.Channel.Register(AccountToRegister, UID, AdminOrNot);
        }
        
        public bool DeleteFavoriteItem(string ItemBarCode) {
            return base.Channel.DeleteFavoriteItem(ItemBarCode);
        }
        
        public bool AddFavoriteItem(string ItemName, string ItemBarCode, int ItemQuantity, decimal ItemPrice, decimal ItemPriceTax, decimal Category, System.DateTime Date) {
            return base.Channel.AddFavoriteItem(ItemName, ItemBarCode, ItemQuantity, ItemPrice, ItemPriceTax, Category, Date);
        }
        
        public bool SaveRegisterClose(string cashierName, decimal moneyInRegister) {
            return base.Channel.SaveRegisterClose(cashierName, moneyInRegister);
        }
        
        public bool SaveRegisterOpen(string cashierName, decimal moneyInRegister) {
            return base.Channel.SaveRegisterOpen(cashierName, moneyInRegister);
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> SearchWarehouseInventoryItems(int WarehouseID) {
            return base.Channel.SearchWarehouseInventoryItems(WarehouseID);
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> SearchInventoryItems(string ItemName, string ItemBarCode) {
            return base.Channel.SearchInventoryItems(ItemName, ItemBarCode);
        }
        
        public Dependencies.Item SearchInventoryItemsWithBarCode(string ItemBarCode) {
            return base.Channel.SearchInventoryItemsWithBarCode(ItemBarCode);
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Bill>, System.Data.DataTable> RetrieveUnPortedBills() {
            return base.Channel.RetrieveUnPortedBills();
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Bill>, System.Data.DataTable> RetrievePortedBills() {
            return base.Channel.RetrievePortedBills();
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Bill>, System.Data.DataTable> RetrieveVendorBills() {
            return base.Channel.RetrieveVendorBills();
        }
        
        public System.Data.DataTable RetrieveTaxZReport() {
            return base.Channel.RetrieveTaxZReport();
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Bill>, System.Data.DataTable> RetrieveBills() {
            return base.Channel.RetrieveBills();
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> RetrieveCapitalRevenue() {
            return base.Channel.RetrieveCapitalRevenue();
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> RetrieveExports() {
            return base.Channel.RetrieveExports();
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> RetrieveImports() {
            return base.Channel.RetrieveImports();
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> RetrieveLeastBoughtItems() {
            return base.Channel.RetrieveLeastBoughtItems();
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> RetrieveMostBoughtItems() {
            return base.Channel.RetrieveMostBoughtItems();
        }
        
        public int RetrieveAccountAuthority(string UserID) {
            return base.Channel.RetrieveAccountAuthority(UserID);
        }
        
        public Dependencies.Account RetrieveUserPermissions(string UserID) {
            return base.Channel.RetrieveUserPermissions(UserID);
        }
        
        public Dependencies.Item RetrieveItemPictureFromBarCode(string ItemBarCode) {
            return base.Channel.RetrieveItemPictureFromBarCode(ItemBarCode);
        }
        
        public Dependencies.Item RetrieveItemsQuantityDates(string ItemBarCode) {
            return base.Channel.RetrieveItemsQuantityDates(ItemBarCode);
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> RetrieveItems() {
            return base.Channel.RetrieveItems();
        }
        
        public System.Data.DataTable RetrieveEmployees() {
            return base.Channel.RetrieveEmployees();
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Account>, System.Data.DataTable> RetrieveUsers() {
            return base.Channel.RetrieveUsers();
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> RetrieveVendorBillItems(int BillNumber) {
            return base.Channel.RetrieveVendorBillItems(BillNumber);
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> RetrieveBillItems(int BillNumber) {
            return base.Channel.RetrieveBillItems(BillNumber);
        }
        
        public System.Data.DataTable RetrieveBillItemsProfit(System.DateTime Date1, System.DateTime Date2, int ItemTypeID, string CashierName) {
            return base.Channel.RetrieveBillItemsProfit(Date1, Date2, ItemTypeID, CashierName);
        }
        
        public System.Data.DataTable RetrieveReturnedItems() {
            return base.Channel.RetrieveReturnedItems();
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> RetrieveFavoriteItems(int Category) {
            return base.Channel.RetrieveFavoriteItems(Category);
        }
        
        public decimal GetCapitalAmount() {
            return base.Channel.GetCapitalAmount();
        }
        
        public decimal GetOpenRegisterAmount() {
            return base.Channel.GetOpenRegisterAmount();
        }
        
        public decimal GetTotalSalesAmountCloseCash() {
            return base.Channel.GetTotalSalesAmountCloseCash();
        }
        
        public decimal GetTotalSalesAmount() {
            return base.Channel.GetTotalSalesAmount();
        }
        
        public string GetLastOpenRegisterDate() {
            return base.Channel.GetLastOpenRegisterDate();
        }
        
        public bool InsertExpense(string ExpenseName, decimal ExpenseCost, string EmployeeName, System.DateTime Date) {
            return base.Channel.InsertExpense(ExpenseName, ExpenseCost, EmployeeName, Date);
        }
        
        public bool InsertDeduction(int EmployeeID, System.DateTime Date, decimal Deduction) {
            return base.Channel.InsertDeduction(EmployeeID, Date, Deduction);
        }
        
        public bool InsertDayOff(int EmployeeID, System.DateTime Date) {
            return base.Channel.InsertDayOff(EmployeeID, Date);
        }
        
        public bool InsertAbsence(int EmployeeID, System.DateTime Date, int Hours) {
            return base.Channel.InsertAbsence(EmployeeID, Date, Hours);
        }
        
        public bool InsertEmployee(string EmployeeName, decimal Salary, string Phone, string Address) {
            return base.Channel.InsertEmployee(EmployeeName, Salary, Phone, Address);
        }
        
        public bool InsertItem(Dependencies.Item ItemToInsert) {
            return base.Channel.InsertItem(ItemToInsert);
        }
        
        public bool DeleteItemType(int ItemTypeID) {
            return base.Channel.DeleteItemType(ItemTypeID);
        }
        
        public bool DeleteWarehouse(int WarehouseID) {
            return base.Channel.DeleteWarehouse(WarehouseID);
        }
        
        public bool DeleteFavoriteCategory(int FavoriteCategoryID) {
            return base.Channel.DeleteFavoriteCategory(FavoriteCategoryID);
        }
        
        public bool UpdateItemTypes(int ItemTypeID, string ItemTypeName) {
            return base.Channel.UpdateItemTypes(ItemTypeID, ItemTypeName);
        }
        
        public bool UpdateWarehouses(int WarehouseID, string WarehouseName) {
            return base.Channel.UpdateWarehouses(WarehouseID, WarehouseName);
        }
        
        public bool UpdateFavoriteCategories(int FavoriteCategoryID, string FavoriteCategory) {
            return base.Channel.UpdateFavoriteCategories(FavoriteCategoryID, FavoriteCategory);
        }
        
        public bool InsertItemType(string ItemTypeName) {
            return base.Channel.InsertItemType(ItemTypeName);
        }
        
        public bool InsertWarehouse(string WarehouseName) {
            return base.Channel.InsertWarehouse(WarehouseName);
        }
        
        public bool InsertFavoriteCategory(string FavoriteCategory) {
            return base.Channel.InsertFavoriteCategory(FavoriteCategory);
        }
        
        public bool DeletesCustomer(string CustomerID) {
            return base.Channel.DeletesCustomer(CustomerID);
        }
        
        public bool RegisterCustomer(Dependencies.Customer CustomerToInsert) {
            return base.Channel.RegisterCustomer(CustomerToInsert);
        }
        
        public bool RegisterVendor(Dependencies.Customer CustomerToInsert) {
            return base.Channel.RegisterVendor(CustomerToInsert);
        }
        
        public bool DeleteAbsence(int AbsenceID) {
            return base.Channel.DeleteAbsence(AbsenceID);
        }
        
        public bool DeleteEmployee(int EmployeeID) {
            return base.Channel.DeleteEmployee(EmployeeID);
        }
        
        public bool DeleteUser(Dependencies.Account UserToUpdate, string cashierName) {
            return base.Channel.DeleteUser(UserToUpdate, cashierName);
        }
        
        public bool AddSaleOnItems(System.Collections.Generic.List<Dependencies.Item> saleItems) {
            return base.Channel.AddSaleOnItems(saleItems);
        }
        
        public bool AddItemToCustomer(string ItemBarCode, int CustomerID, decimal CustomerPrice) {
            return base.Channel.AddItemToCustomer(ItemBarCode, CustomerID, CustomerPrice);
        }
        
        public bool AddVendorBill(Dependencies.Bill billToAdd, string cashierName) {
            return base.Channel.AddVendorBill(billToAdd, cashierName);
        }
        
        public bool PayBill(Dependencies.Bill billToAdd, string cashierName) {
            return base.Channel.PayBill(billToAdd, cashierName);
        }
        
        public bool UpdateEmployee(int EmployeeID, string EmployeeName, decimal Salary, string Phone, string Address) {
            return base.Channel.UpdateEmployee(EmployeeID, EmployeeName, Salary, Phone, Address);
        }
        
        public bool UpdateUser(Dependencies.Account UserToUpdate, string cashierName, int AdminOrNot) {
            return base.Channel.UpdateUser(UserToUpdate, cashierName, AdminOrNot);
        }
        
        public bool UpdateBill(int BillNumber, string CashierName, decimal TotalAmount, decimal PaidAmount, decimal RemainderAmount) {
            return base.Channel.UpdateBill(BillNumber, CashierName, TotalAmount, PaidAmount, RemainderAmount);
        }
        
        public bool ReturnItem(string ItemName, string ItemBarCode, int ItemQuantity, string cashierName) {
            return base.Channel.ReturnItem(ItemName, ItemBarCode, ItemQuantity, cashierName);
        }
        
        public bool UpdateItemWarehouse(System.Collections.Generic.List<Dependencies.Item> ItemsToUpdate, string EmployeeName, int EntryExitType) {
            return base.Channel.UpdateItemWarehouse(ItemsToUpdate, EmployeeName, EntryExitType);
        }
        
        public bool UpdateItem(Dependencies.Item ItemToUpdate) {
            return base.Channel.UpdateItem(ItemToUpdate);
        }
        
        public bool UpdateItemQuantity(Dependencies.Item ItemToUpdate) {
            return base.Channel.UpdateItemQuantity(ItemToUpdate);
        }
        
        public bool DeleteItem(string ItemBarCode) {
            return base.Channel.DeleteItem(ItemBarCode);
        }
        
        public Dependencies.Bill RetrieveLastVendorBillNumberToday(System.DateTime Date) {
            return base.Channel.RetrieveLastVendorBillNumberToday(Date);
        }
        
        public Dependencies.Bill RetrieveLastBillNumberToday() {
            return base.Channel.RetrieveLastBillNumberToday();
        }
        
        public System.Collections.Generic.List<Dependencies.Item> RetrieveItemsQuantity(string ItemBarCode) {
            return base.Channel.RetrieveItemsQuantity(ItemBarCode);
        }
        
        public System.Collections.Generic.List<Dependencies.Item> RetrieveSaleItemsQuantity() {
            return base.Channel.RetrieveSaleItemsQuantity();
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> RetrieveExpireStockToday(System.DateTime Date) {
            return base.Channel.RetrieveExpireStockToday(Date);
        }
        
        public System.Collections.Generic.List<Dependencies.Item> RetrieveSaleToday(System.DateTime Date, int QuantityEnd) {
            return base.Channel.RetrieveSaleToday(Date, QuantityEnd);
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Bill>, System.Data.DataTable> SearchTodayBills(System.DateTime Date) {
            return base.Channel.SearchTodayBills(Date);
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Bill>, System.Data.DataTable> SearchBills(int BillNumber) {
            return base.Channel.SearchBills(BillNumber);
        }
        
        public int GetItemQuantity(string ItemBarCode) {
            return base.Channel.GetItemQuantity(ItemBarCode);
        }
        
        public System.Data.DataTable RetrieveAbsence(System.DateTime Date1, System.DateTime Date2) {
            return base.Channel.RetrieveAbsence(Date1, Date2);
        }
        
        public System.Data.DataTable SearchExpenses(System.DateTime Date1, System.DateTime Date2, string ExpenseName, string EmployeeID) {
            return base.Channel.SearchExpenses(Date1, Date2, ExpenseName, EmployeeID);
        }
        
        public System.Tuple<System.Collections.Generic.List<Dependencies.Item>, System.Data.DataTable> SearchItems(string ItemName, string ItemBarCode, int ItemType) {
            return base.Channel.SearchItems(ItemName, ItemBarCode, ItemType);
        }
        
        public System.Data.DataTable SearchCustomers(string customerName, string customerID, string itemName) {
            return base.Channel.SearchCustomers(customerName, customerID, itemName);
        }
        
        public System.Tuple<Dependencies.Customer, System.Data.DataTable> SearchCustomersInfo(string customerName, string customerID) {
            return base.Channel.SearchCustomersInfo(customerName, customerID);
        }
    }
}
